import { MD3DarkTheme } from 'react-native-paper';

export const appColors = {
  background: '#070B14',
  backgroundElevated: '#0D1320',
  surface: '#121A29',
  surfaceStrong: '#172235',
  surfaceMuted: '#1C2940',
  surfaceAccent: '#1A2440',
  border: 'rgba(154, 175, 207, 0.16)',
  borderStrong: 'rgba(154, 175, 207, 0.26)',
  textPrimary: '#F5F7FB',
  textSecondary: '#B2BED1',
  textTertiary: '#8A97AD',
  accent: '#7C8CFF',
  accentStrong: '#94A0FF',
  accentSoft: 'rgba(124, 140, 255, 0.18)',
  success: '#39C29A',
  successSoft: 'rgba(57, 194, 154, 0.18)',
  warning: '#F5B86A',
  warningSoft: 'rgba(245, 184, 106, 0.16)',
  danger: '#FF7A8A',
  dangerSoft: 'rgba(255, 122, 138, 0.18)',
  info: '#72B8FF',
  infoSoft: 'rgba(114, 184, 255, 0.18)',
  white: '#FFFFFF',
  navBackground: 'rgba(11, 16, 27, 0.92)',
};

export const appTheme = {
  ...MD3DarkTheme,
  roundness: 7,
  colors: {
    ...MD3DarkTheme.colors,
    primary: appColors.accent,
    onPrimary: appColors.white,
    primaryContainer: appColors.accentSoft,
    onPrimaryContainer: appColors.textPrimary,
    secondary: appColors.success,
    onSecondary: appColors.white,
    secondaryContainer: appColors.successSoft,
    onSecondaryContainer: appColors.textPrimary,
    error: appColors.danger,
    onError: appColors.white,
    background: appColors.background,
    onBackground: appColors.textPrimary,
    surface: appColors.surface,
    onSurface: appColors.textPrimary,
    surfaceVariant: appColors.surfaceStrong,
    onSurfaceVariant: appColors.textSecondary,
    outline: appColors.borderStrong,
    outlineVariant: appColors.border,
    elevation: {
      level0: appColors.background,
      level1: appColors.surface,
      level2: appColors.surfaceStrong,
      level3: appColors.surfaceMuted,
      level4: appColors.surfaceAccent,
      level5: appColors.surfaceAccent,
    },
  },
};

